import { NextRequest, NextResponse } from 'next/server'
import { createClient, createServiceClient } from '@/lib/supabase/server'

export const dynamic = 'force-dynamic'

interface DemoMessage {
  gmail_id: string
  received_at: string
  sender: string
  sender_phone: string
  sms_text: string
  action: string
  vehicle_number: string | null
  vehicle_id: null
  driver_id: null
  target: string | null
  confidence: 'high' | 'medium' | 'low'
  reason: string | null
  rule_name: string | null
  device_name: null
  result: string | null
  success: null
  processed: boolean
  translated_text: string | null
  source_language: string | null
  direction: 'inbound' | 'outbound'
  source: 'gmail'
  twilio_sid: null
  recipient_phone: string | null
}

export async function POST(req: NextRequest) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const service = await createServiceClient()

  try {
    // Delete existing demo messages
    await service.from('sms_messages').delete().like('gmail_id', 'demo_%')

    // Generate realistic timestamps across last 3 days
    const now = new Date()
    const threeDaysAgo = new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000)

    const randomTimestamp = (): string => {
      const time = new Date(threeDaysAgo.getTime() + Math.random() * (now.getTime() - threeDaysAgo.getTime()))
      return time.toISOString()
    }

    // Demo data with realistic conversations
    const messages: DemoMessage[] = [
      // 1. Carlos (2135551234) - Driver support conversation
      {
        gmail_id: 'demo_carlos_001',
        received_at: randomTimestamp(),
        sender: 'Carlos',
        sender_phone: '2135551234',
        sms_text: "Cab #6020 tablet frozen can't dispatch",
        action: 'reboot_driver',
        vehicle_number: '6020',
        vehicle_id: null,
        driver_id: null,
        target: 'driver',
        confidence: 'high',
        reason: null,
        rule_name: null,
        device_name: null,
        result: 'Intent parsed: reboot_driver for vehicle 6020',
        success: null,
        processed: true,
        translated_text: null,
        source_language: null,
        direction: 'inbound',
        source: 'gmail',
        twilio_sid: null,
        recipient_phone: null,
      },
      {
        gmail_id: 'demo_carlos_002',
        received_at: randomTimestamp(),
        sender: 'Carlos',
        sender_phone: '2135551234',
        sms_text: 'Still frozen after restart',
        action: 'unknown',
        vehicle_number: '6020',
        vehicle_id: null,
        driver_id: null,
        target: null,
        confidence: 'low',
        reason: 'Unclear if issue persists',
        rule_name: null,
        device_name: null,
        result: null,
        success: null,
        processed: true,
        translated_text: null,
        source_language: null,
        direction: 'inbound',
        source: 'gmail',
        twilio_sid: null,
        recipient_phone: null,
      },
      {
        gmail_id: 'demo_carlos_003',
        received_at: randomTimestamp(),
        sender: 'Carlos',
        sender_phone: '2135551234',
        sms_text: 'NOP cab 6020',
        action: 'reboot_pim',
        vehicle_number: '6020',
        vehicle_id: null,
        driver_id: null,
        target: 'pim',
        confidence: 'high',
        reason: 'NOP keyword matched: payment issue',
        rule_name: 'Payment Reboot',
        device_name: null,
        result: 'Intent parsed: reboot_pim for vehicle 6020 (rule: Payment Reboot)',
        success: null,
        processed: true,
        translated_text: null,
        source_language: null,
        direction: 'inbound',
        source: 'gmail',
        twilio_sid: null,
        recipient_phone: null,
      },

      // Outbound reply to Carlos
      {
        gmail_id: 'demo_carlos_outbound_001',
        received_at: randomTimestamp(),
        sender: 'LA Yellow Support',
        sender_phone: '2135551234',
        sms_text: 'Rebooting driver tablet on cab 6020 now. Please wait 2 minutes.',
        action: null as unknown as string,
        vehicle_number: '6020',
        vehicle_id: null,
        driver_id: null,
        target: null,
        confidence: 'high',
        reason: null,
        rule_name: null,
        device_name: null,
        result: null,
        success: null,
        processed: true,
        translated_text: null,
        source_language: null,
        direction: 'outbound',
        source: 'gmail',
        twilio_sid: null,
        recipient_phone: '2135551234',
      },

      // 2. Armen (2135555678) - Armenian transliterated
      {
        gmail_id: 'demo_armen_001',
        received_at: randomTimestamp(),
        sender: 'Armen',
        sender_phone: '2135555678',
        sms_text: "Taxin 4501 chisht chi ashkhatum, payment@ chi ashkhatum",
        action: 'reboot_pim',
        vehicle_number: '4501',
        vehicle_id: null,
        driver_id: null,
        target: 'pim',
        confidence: 'medium',
        reason: 'Payment issue detected in transliterated Armenian',
        rule_name: null,
        device_name: null,
        result: 'Intent parsed: reboot_pim for vehicle 4501',
        success: null,
        processed: true,
        translated_text: 'Taxi 4501 is not working properly, payment is not working',
        source_language: 'Armenian',
        direction: 'inbound',
        source: 'gmail',
        twilio_sid: null,
        recipient_phone: null,
      },
      {
        gmail_id: 'demo_armen_002',
        received_at: randomTimestamp(),
        sender: 'Armen',
        sender_phone: '2135555678',
        sms_text: 'Shnorhakalutyun, hima ashkhatum e',
        action: 'auto_reply',
        vehicle_number: null,
        vehicle_id: null,
        driver_id: null,
        target: null,
        confidence: 'high',
        reason: null,
        rule_name: null,
        device_name: null,
        result: 'Intent parsed: auto_reply',
        success: null,
        processed: true,
        translated_text: 'Thank you, it\'s working now',
        source_language: 'Armenian',
        direction: 'inbound',
        source: 'gmail',
        twilio_sid: null,
        recipient_phone: null,
      },

      // 3. Maria (2135559012) - Spanish
      {
        gmail_id: 'demo_maria_001',
        received_at: randomTimestamp(),
        sender: 'Maria',
        sender_phone: '2135559012',
        sms_text: 'Taxi #3088 la tableta no prende',
        action: 'reboot_driver',
        vehicle_number: '3088',
        vehicle_id: null,
        driver_id: null,
        target: 'driver',
        confidence: 'high',
        reason: null,
        rule_name: null,
        device_name: null,
        result: 'Intent parsed: reboot_driver for vehicle 3088',
        success: null,
        processed: true,
        translated_text: 'Taxi #3088 the tablet won\'t turn on',
        source_language: 'Spanish',
        direction: 'inbound',
        source: 'gmail',
        twilio_sid: null,
        recipient_phone: null,
      },
      {
        gmail_id: 'demo_maria_002',
        received_at: randomTimestamp(),
        sender: 'Maria',
        sender_phone: '2135559012',
        sms_text: 'Numero de lease 25343',
        action: 'unknown',
        vehicle_number: null,
        vehicle_id: null,
        driver_id: null,
        target: null,
        confidence: 'low',
        reason: 'Lease number provided without request context',
        rule_name: null,
        device_name: null,
        result: null,
        success: null,
        processed: true,
        translated_text: 'Lease number 25343',
        source_language: 'Spanish',
        direction: 'inbound',
        source: 'gmail',
        twilio_sid: null,
        recipient_phone: null,
      },
      {
        gmail_id: 'demo_maria_003',
        received_at: randomTimestamp(),
        sender: 'Maria',
        sender_phone: '2135559012',
        sms_text: 'Ya funciona gracias',
        action: 'auto_reply',
        vehicle_number: null,
        vehicle_id: null,
        driver_id: null,
        target: null,
        confidence: 'high',
        reason: null,
        rule_name: null,
        device_name: null,
        result: 'Intent parsed: auto_reply',
        success: null,
        processed: true,
        translated_text: 'It\'s working now, thanks',
        source_language: 'Spanish',
        direction: 'inbound',
        source: 'gmail',
        twilio_sid: null,
        recipient_phone: null,
      },

      // 4. Mike (3105551111) - English
      {
        gmail_id: 'demo_mike_001',
        received_at: randomTimestamp(),
        sender: 'Mike',
        sender_phone: '3105551111',
        sms_text: 'Need to clear bluetooth on PIM for cab 7712',
        action: 'clear_pim_bt',
        vehicle_number: '7712',
        vehicle_id: null,
        driver_id: null,
        target: 'pim',
        confidence: 'high',
        reason: null,
        rule_name: null,
        device_name: null,
        result: 'Intent parsed: clear_pim_bt for vehicle 7712',
        success: null,
        processed: true,
        translated_text: null,
        source_language: null,
        direction: 'inbound',
        source: 'gmail',
        twilio_sid: null,
        recipient_phone: null,
      },
      {
        gmail_id: 'demo_mike_002',
        received_at: randomTimestamp(),
        sender: 'Mike',
        sender_phone: '3105551111',
        sms_text: 'Also please put 7712 in kiosk mode',
        action: 'kiosk_enter',
        vehicle_number: '7712',
        vehicle_id: null,
        driver_id: null,
        target: 'pim',
        confidence: 'high',
        reason: null,
        rule_name: null,
        device_name: null,
        result: 'Intent parsed: kiosk_enter for vehicle 7712',
        success: null,
        processed: true,
        translated_text: null,
        source_language: null,
        direction: 'inbound',
        source: 'gmail',
        twilio_sid: null,
        recipient_phone: null,
      },

      // Outbound reply to Mike
      {
        gmail_id: 'demo_mike_outbound_001',
        received_at: randomTimestamp(),
        sender: 'LA Yellow Support',
        sender_phone: '3105551111',
        sms_text: 'Bluetooth cleared and kiosk mode enabled on 7712.',
        action: null as unknown as string,
        vehicle_number: '7712',
        vehicle_id: null,
        driver_id: null,
        target: null,
        confidence: 'high',
        reason: null,
        rule_name: null,
        device_name: null,
        result: null,
        success: null,
        processed: true,
        translated_text: null,
        source_language: null,
        direction: 'outbound',
        source: 'gmail',
        twilio_sid: null,
        recipient_phone: '3105551111',
      },

      // 5. Amir (2135553333) - Farsi transliterated
      {
        gmail_id: 'demo_amir_001',
        received_at: randomTimestamp(),
        sender: 'Amir',
        sender_phone: '2135553333',
        sms_text: 'Cab 2200 tablet kharab shode, lotfan reboot konid',
        action: 'reboot_driver',
        vehicle_number: '2200',
        vehicle_id: null,
        driver_id: null,
        target: 'driver',
        confidence: 'medium',
        reason: 'Reboot request detected in transliterated Farsi',
        rule_name: null,
        device_name: null,
        result: 'Intent parsed: reboot_driver for vehicle 2200',
        success: null,
        processed: true,
        translated_text: 'Cab 2200 tablet is broken, please reboot',
        source_language: 'Farsi',
        direction: 'inbound',
        source: 'gmail',
        twilio_sid: null,
        recipient_phone: null,
      },
      {
        gmail_id: 'demo_amir_002',
        received_at: randomTimestamp(),
        sender: 'Amir',
        sender_phone: '2135553333',
        sms_text: 'payment ham kar nemikonad',
        action: 'reboot_pim',
        vehicle_number: null,
        vehicle_id: null,
        driver_id: null,
        target: 'pim',
        confidence: 'high',
        reason: 'Payment issue indicated in Farsi',
        rule_name: null,
        device_name: null,
        result: 'Intent parsed: reboot_pim',
        success: null,
        processed: true,
        translated_text: 'Payment also doesn\'t work',
        source_language: 'Farsi',
        direction: 'inbound',
        source: 'gmail',
        twilio_sid: null,
        recipient_phone: null,
      },
      {
        gmail_id: 'demo_amir_003',
        received_at: randomTimestamp(),
        sender: 'Amir',
        sender_phone: '2135553333',
        sms_text: 'mamnoon, dorost shod',
        action: 'auto_reply',
        vehicle_number: null,
        vehicle_id: null,
        driver_id: null,
        target: null,
        confidence: 'high',
        reason: null,
        rule_name: null,
        device_name: null,
        result: 'Intent parsed: auto_reply',
        success: null,
        processed: true,
        translated_text: 'Thanks, it\'s fixed',
        source_language: 'Farsi',
        direction: 'inbound',
        source: 'gmail',
        twilio_sid: null,
        recipient_phone: null,
      },

      // 6. Tony (8185554444) - English
      {
        gmail_id: 'demo_tony_001',
        received_at: randomTimestamp(),
        sender: 'Tony',
        sender_phone: '8185554444',
        sms_text: 'Cab 1850 dispatch app keeps crashing',
        action: 'clear_dispatch',
        vehicle_number: '1850',
        vehicle_id: null,
        driver_id: null,
        target: 'driver',
        confidence: 'high',
        reason: null,
        rule_name: null,
        device_name: null,
        result: 'Intent parsed: clear_dispatch for vehicle 1850',
        success: null,
        processed: true,
        translated_text: null,
        source_language: null,
        direction: 'inbound',
        source: 'gmail',
        twilio_sid: null,
        recipient_phone: null,
      },
      {
        gmail_id: 'demo_tony_002',
        received_at: randomTimestamp(),
        sender: 'Tony',
        sender_phone: '8185554444',
        sms_text: 'Can someone remote into the driver tablet on 1850?',
        action: 'support_driver',
        vehicle_number: '1850',
        vehicle_id: null,
        driver_id: null,
        target: 'driver',
        confidence: 'high',
        reason: null,
        rule_name: null,
        device_name: null,
        result: 'Intent parsed: support_driver for vehicle 1850',
        success: null,
        processed: true,
        translated_text: null,
        source_language: null,
        direction: 'inbound',
        source: 'gmail',
        twilio_sid: null,
        recipient_phone: null,
      },

      // 7. Unknown driver (2135557777) - English
      {
        gmail_id: 'demo_unknown_001',
        received_at: randomTimestamp(),
        sender: 'driver',
        sender_phone: '2135557777',
        sms_text: 'reboot',
        action: 'reboot_driver',
        vehicle_number: null,
        vehicle_id: null,
        driver_id: null,
        target: 'driver',
        confidence: 'low',
        reason: 'No vehicle number provided',
        rule_name: null,
        device_name: null,
        result: null,
        success: null,
        processed: true,
        translated_text: null,
        source_language: null,
        direction: 'inbound',
        source: 'gmail',
        twilio_sid: null,
        recipient_phone: null,
      },
      {
        gmail_id: 'demo_unknown_002',
        received_at: randomTimestamp(),
        sender: 'driver',
        sender_phone: '2135557777',
        sms_text: 'sorry cab 5500 please reboot',
        action: 'reboot_driver',
        vehicle_number: '5500',
        vehicle_id: null,
        driver_id: null,
        target: 'driver',
        confidence: 'high',
        reason: null,
        rule_name: null,
        device_name: null,
        result: 'Intent parsed: reboot_driver for vehicle 5500',
        success: null,
        processed: true,
        translated_text: null,
        source_language: null,
        direction: 'inbound',
        source: 'gmail',
        twilio_sid: null,
        recipient_phone: null,
      },

      // 8. Sergei (3235558888) - Russian
      {
        gmail_id: 'demo_sergei_001',
        received_at: randomTimestamp(),
        sender: 'Sergei',
        sender_phone: '3235558888',
        sms_text: 'Кab 9100 планшет не работает, оплата не проходит',
        action: 'reboot_pim',
        vehicle_number: '9100',
        vehicle_id: null,
        driver_id: null,
        target: 'pim',
        confidence: 'high',
        reason: 'Payment failure detected in Russian',
        rule_name: null,
        device_name: null,
        result: 'Intent parsed: reboot_pim for vehicle 9100',
        success: null,
        processed: true,
        translated_text: 'Cab 9100 tablet not working, payment not going through',
        source_language: 'Russian',
        direction: 'inbound',
        source: 'gmail',
        twilio_sid: null,
        recipient_phone: null,
      },
      {
        gmail_id: 'demo_sergei_002',
        received_at: randomTimestamp(),
        sender: 'Sergei',
        sender_phone: '3235558888',
        sms_text: 'Всё заработало спасибо',
        action: 'auto_reply',
        vehicle_number: null,
        vehicle_id: null,
        driver_id: null,
        target: null,
        confidence: 'high',
        reason: null,
        rule_name: null,
        device_name: null,
        result: 'Intent parsed: auto_reply',
        success: null,
        processed: true,
        translated_text: 'Everything works now, thanks',
        source_language: 'Russian',
        direction: 'inbound',
        source: 'gmail',
        twilio_sid: null,
        recipient_phone: null,
      },
    ]

    // Insert all messages
    const { error } = await service.from('sms_messages').insert(messages)

    if (error) {
      return NextResponse.json({ success: false, error: error.message }, { status: 500 })
    }

    return NextResponse.json({
      success: true,
      inserted: messages.length,
      message: `Seeded ${messages.length} demo SMS messages across 8 conversations`,
    })
  } catch (err) {
    const msg = err instanceof Error ? err.message : 'Unknown error'
    return NextResponse.json({ success: false, error: msg }, { status: 500 })
  }
}
